### ISSUE TITLE
[Discuss]: Multiple authenticated model

### ISSUE THREAD

**Issue by CanerErgez** [cjmellor/blockade#4]
### What happened?

Hi, i have a question about this package. If i want to use this package 2 or more authenticable model. For example : users, employees and contacts. I cannot use this package because this package must be a one user model. 

Maybe you didn't think this case and maybe you want change this logic.

Actually this issue is not bug but i don't use other issue types.

### How to reproduce the bug

Should use 2 or more authenticable model. For example : users, employees and contacts.

### Package Version

1.1.1

### PHP Version

8.2.0

### Laravel Version

9.0.0

### Which operating systems does with happen with?

macOS, Windows, Linux

**Comment by cjmellor** [comment]
Hi,

My intention for this package is just to have it work on a User model. 

If you need the functionality you require, you're welcome to fork the package and add it yourself.
